-- ⚠️  APAGA TODOS OS DADOS — rode antes de começar do zero
TRUNCATE TABLE transaction_splits RESTART IDENTITY CASCADE;
TRUNCATE TABLE transaction_items  RESTART IDENTITY CASCADE;
TRUNCATE TABLE transactions       RESTART IDENTITY CASCADE;
TRUNCATE TABLE sync_progress      RESTART IDENTITY CASCADE;
